In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris

df = load_iris()
X = df.data
y = df.target

print("Feature names:", df.feature_names)
print("Target names:", df.target_names)


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [3]:
type(X)

numpy.ndarray

In [4]:
q_pt = np.array([5.5, 3, 3.6, 1.4])
q_pt

array([5.5, 3. , 3.6, 1.4])

In [5]:
type(q_pt)

numpy.ndarray

In [6]:
np.argmax(q_pt)

0

In [7]:
sorted_qpt = sorted(q_pt, reverse = False)
sorted_qpt

[1.4, 3.0, 3.6, 5.5]

In [8]:
sorted_qpt_indices = np.argsort(q_pt)
# sorted_qpt_indices = sorted_qpt_indices[::-1]
sorted_qpt_indices

array([3, 1, 2, 0])

In [9]:
ls = sorted_qpt_indices[:2]
ls

array([3, 1])

In [10]:
labels = y[ls]
labels

array([0, 0])

# KNN

In [11]:
K = 5

In [12]:
query = np.array([5.5, 3, 3.6, 1.4])

In [13]:
no_of_features = len(X[0])
no_of_features

4

In [14]:
distance = []
"""
    Calculates distance between given query point to every other point in dataset.
    And Stores in the distance array.
"""
for data_point in X:
    dist = 0
    for i in range(no_of_features):
        dist += (query[i] - data_point[i])**2
    dist = np.sqrt(dist)
    distance.append(dist)

In [15]:
distance

[2.5865034312755126,
 2.5768197453450252,
 2.7221315177632395,
 2.582634314028992,
 2.6248809496813377,
 2.3302360395462087,
 2.6495282598983545,
 2.5019992006393608,
 2.7386127875258306,
 2.543619468395381,
 2.5199206336708304,
 2.467792535850613,
 2.649528259898354,
 3.0626785662227105,
 2.879236009777594,
 2.7221315177632404,
 2.6664583251946765,
 2.541653005427767,
 2.345207879911715,
 2.5337718918639855,
 2.2847319317591728,
 2.4617067250182343,
 3.0610455730027937,
 2.1610182784974308,
 2.23159136044214,
 2.3853720883753127,
 2.3259406699226015,
 2.4879710609249455,
 2.5553864678361276,
 2.473863375370596,
 2.437211521390788,
 2.3622023622035435,
 2.7202941017470885,
 2.778488797889961,
 2.493992782667985,
 2.736786436680802,
 2.641968962724581,
 2.692582403567252,
 2.8178005607210737,
 2.483948469674844,
 2.6457513110645903,
 2.826658805020514,
 2.8248893783651066,
 2.2671568097509267,
 2.1656407827707715,
 2.5573423705088847,
 2.4979991993593593,
 2.670205984563738,
 2.52586618

In [16]:
sorted_distance = sorted(distance)
sorted_distance_indices = np.argsort(distance)

In [17]:
sorted_distance

[0.1732050807568875,
 0.5196152422706627,
 0.5196152422706629,
 0.5567764362830019,
 0.5830951894845298,
 0.6082762530298219,
 0.648074069840786,
 0.6480740698407862,
 0.6633249580710798,
 0.66332495807108,
 0.6708203932499367,
 0.6855654600401043,
 0.7,
 0.7280109889280518,
 0.728010988928052,
 0.7549834435270747,
 0.7681145747868604,
 0.8124038404635961,
 0.9110433579144297,
 0.9110433579144297,
 0.9165151389911682,
 0.9273618495495705,
 0.9486832980505138,
 0.9848857801796104,
 0.9949874371066201,
 1.0,
 1.0392304845413263,
 1.0999999999999999,
 1.1224972160321822,
 1.148912529307606,
 1.1661903789690595,
 1.1916375287812984,
 1.2288205727444506,
 1.2569805089976533,
 1.284523257866513,
 1.2922847983320087,
 1.3341664064126335,
 1.3416407864998738,
 1.360147050873544,
 1.3601470508735443,
 1.396424004376894,
 1.4071247279470287,
 1.431782106327635,
 1.4456832294800963,
 1.449137674618944,
 1.4594519519326423,
 1.4866068747318506,
 1.4933184523068073,
 1.6031219541881394,
 1.60623784

In [18]:
sorted_distance_indices

array([ 64,  88,  59,  82,  99,  79,  89,  96,  69,  95,  92,  94,  80,
        81,  61,  71,  67,  53,  66,  84,  90,  98,  55,  57,  93,  97,
        78,  62,  85,  74,  91,  60, 106,  63,  73,  51,  87,  70, 138,
        75,  68,  56,  54,  65, 121, 126, 127,  58, 149, 123,  72, 113,
        83,  86, 101, 142, 119, 133, 146,  76, 114,  77,  50, 110,  52,
       147, 111, 134, 115, 137,  23,  44, 148, 116, 103, 145,  24, 141,
        43,  20, 128,  26,   5, 132,  18,  31,  25, 139, 112, 136,  30,
        21,  11,  29,  39,  27,  34,  46,   7,  10,  48,  19, 124, 140,
        17,   9, 104,  28,  45,  49,   1,   3,   0, 108,   4,  36,  40,
        12,   6,  16,  47, 144, 120,  37,  32,   2,  15,  35,   8, 100,
        33, 129, 143,  38,  42,  41,  14, 102, 125,  22,  13, 130, 107,
       109, 135, 105, 131, 122, 117, 118])

In [19]:
"""
    Picking first K points from the sorted distance array
    and taking their indices and storing in class_labels.
"""
class_labels = y[sorted_distance_indices[:K]]
class_labels

array([1, 1, 1, 1, 1])

In [20]:
"""
    From the collected class_labels perform a simple
    Majority voting algorithm and return the class label.
"""
from collections import Counter
counter = Counter(class_labels)
counter

Counter({1: 5})

In [21]:
max_count = 0
max_count_label = -1
for key, value in counter.items():
    if(value > max_count):
        max_count = value
        max_count_label = key

In [22]:
max_count

5

In [23]:
max_count_label

1

In [24]:
from collections import Counter
from sklearn.metrics import accuracy_score, confusion_matrix
class KNN():
    def __init__(self, K):
        self.K = K

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def euclidean_distance(self, query, data_point):
        dist = 0
        for i in range(len(query)):
            dist += (query[i] - data_point[i])**2
        dist = np.sqrt(dist)
        return dist

    def get_KNeighbours(self, query):
        """
            Calculates distance between given query point to every other point in dataset.
            And Stores in the distance array. Here we are using Euclidean distance.
        """
        distance = []
        no_of_features = self.X_train.shape[1]
        for data_point in self.X_train:
            dist = self.euclidean_distance(query, data_point)
            distance.append(dist)

        """
            Picking first K points from the sorted distance array
            and taking their indices and storing in K_neighbours_indices.
        """
        sorted_distance = sorted(distance)
        sorted_distance_indices = np.argsort(distance)
        K_neighbours_indices = sorted_distance_indices[:self.K]

        return K_neighbours_indices

    def predict_query_point(self, K_neighbours_indices):
        class_labels = self.y_train[K_neighbours_indices]
        class_labels
        """
            From the collected class_labels perform a simple
            Majority voting algorithm and return the class label.
        """

        counter = Counter(class_labels)
        # counter

        max_count = 0
        max_count_label = -1
        for key, value in counter.items():
            if(value > max_count):
                max_count = value
                max_count_label = key

        classified_class_label = max_count_label
        return classified_class_label


    def predict(self, X_test):
        """
            We will get a test set, here we want to classify each point in test set.
            And append it into the predicted labels.
        """
        predicted_class_labels = []

        for query in X_test:
            K_neighbours_indices = self.get_KNeighbours(query)
            classified_class_label = self.predict_query_point(K_neighbours_indices)
            predicted_class_labels.append(classified_class_label)

        return predicted_class_labels

    def get_performance_report(self, X_test, y_test):
        predicted_class_labels = self.predict(X_test)

        accuracy = accuracy_score(y_test, predicted_class_labels)
        conf_matrix = confusion_matrix(y_test, predicted_class_labels)


        print("Accuracy : ", accuracy)
        print("Confusion Matrix : \n", conf_matrix)
        # print("Classification Report : " , classification_report(y_test, y_pred))



In [25]:
from sklearn.model_selection import train_test_split
df = load_iris()
X = df.data
y = df.target

print("Feature names:", df.feature_names)
print("Target names:", df.target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
model = KNN(3)
model.fit(X_train, y_train)

In [28]:
model.predict(X_test)

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0]

In [29]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report


# Create the KNN classifier with K=3
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Print classification report for detailed performance metrics
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=df.target_names))


Accuracy: 100.00%
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Testing on Health Dataset

In [61]:
df = pd.read_csv("/content/drive/MyDrive/MACHINE LEARNING LAB/Dataset/income_classification.csv")

In [62]:
df.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [64]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [65]:
X = df.drop(
    columns = ['income'], axis = 1
)
y = df['income']

In [66]:
for col in X.columns:
    if(X[col].dtype == 'object'):
        X.drop(columns = [col], inplace = True)

In [68]:
from sklearn.preprocessing import LabelEncoder

lr = LabelEncoder()

if y.dtype == 'object':
    y = lr.fit_transform(y)

In [80]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [82]:
X_train

array([[ 0.24480847, -0.42128688, -0.03037346, -0.14480353, -0.2171271 ,
        -0.03408696],
       [ 0.97418341, -0.13858643, -1.58622073, -0.14480353, -0.2171271 ,
        -0.43759532],
       [-0.33869149, -0.16098163, -0.41933527, -0.14480353, -0.2171271 ,
        -0.03408696],
       ...,
       [-0.77631645,  0.5726248 , -0.03037346, -0.14480353, -0.2171271 ,
        -0.03408696],
       [ 0.53655844, -0.88077217,  0.35858836, -0.14480353, -0.2171271 ,
        -0.03408696],
       [ 1.48474587, -0.12827421,  1.52547382, -0.14480353, -0.2171271 ,
        -2.6972421 ]])

In [70]:
# X = X.to_numpy()
# y = y.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [81]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [83]:
model = KNN(3)
model.fit(X_train, y_train)

In [84]:
model.predict(X_test)

KeyboardInterrupt: 

In [85]:
model.get_performance_report(X_test, y_test)

KeyboardInterrupt: 

In [86]:

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Print classification report for detailed performance metrics
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 80.81%
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.91      0.88      7479
           1       0.61      0.49      0.54      2290

    accuracy                           0.81      9769
   macro avg       0.73      0.70      0.71      9769
weighted avg       0.80      0.81      0.80      9769

